version: '2'
services:
    elastic1:
        image: micek/elastic1:latest
        hostname: elastic1
        networks:
          app_net:
            ipv4_address: 192.168.20.1
        ports:
            - "9200"
            - "9300"
        volumes:
            - ./elastic1/config/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
        environment:
            ES_JAVA_OPTS: "-Des.path.conf=/etc/elasticsearch"
        # command: "gosu elasticsearch:elasticsearch bash -c '/usr/share/elasticsearch/bin/elasticsearch --path.conf=/etc/elasticsearch'"
    elastic2:
        image: micek/elastic2:latest
        hostname: elastic2
        networks:
          app_net:
            ipv4_address: 192.168.20.2
        ports:
            - "9200"
            - "9300"
        volumes:
            - ./elastic2/config/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
        environment:
            ES_JAVA_OPTS: "-Des.path.conf=/etc/elasticsearch"
        # command: "gosu elasticsearch:elasticsearch bash -c '/usr/share/elasticsearch/bin/elasticsearch --path.conf=/etc/elasticsearch'"
    elastic5:
        image: micek/elastic5:latest
        hostname: elastic5
        networks:
          app_net:
            ipv4_address: 192.168.20.3
        ports:
            - "9200"
            - "9300"
        volumes:
            - ./elastic5/config/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
        environment:
            ES_JAVA_OPTS: "-Xms1g -Xmx1g"
        # command: "/elasticsearch-5.0.0-alpha2/bin/elasticsearch"
    syslogng38-elastic1:
        image: micek/syslogng38-elastic1:latest
        hostname: slng-elastic1
        networks:
          app_net:
            ipv4_address: 192.168.20.11
        ports:
            - "5555"
        # volumes:
        depends_on:
            - elastic1
        command: "/install/syslog-ng/sbin/syslog-ng -Fedv -f /install/syslog-ng/syslog-ng.conf --enable-core"
    syslogng38-elastic2:
        image: micek/syslogng38-elastic2:latest
        hostname: slng-elastic2
        networks:
          app_net:
            ipv4_address: 192.168.20.12
        ports:
            - "5555"
        # volumes:
        depends_on:
            - elastic2
        command: "/install/syslog-ng/sbin/syslog-ng -Fedv -f /install/syslog-ng/syslog-ng.conf --enable-core"
    syslogng38-elastic5:
        image: micek/syslogng38-elastic5:latest
        hostname: slng-elastic5
        networks:
          app_net:
            ipv4_address: 192.168.20.13
        ports:
            - "5555"
        # volumes:
        depends_on:
            - elastic5
        command: "/install/syslog-ng/sbin/syslog-ng -Fedv -f /install/syslog-ng/syslog-ng.conf --enable-core"
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 192.168.20.0/24
        gateway: 192.168.20.254
